root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - jest
  - tsc
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - prettier
rules:
  "tsc/config":
    - error
    - configFile: "tsconfig.json"
overrides:
  - files: [jest.config.js]
    env:
      commonjs: true
