name: CI
on:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - run: yarn lint
      - run: yarn test
      - id: format
        run: |
          yarn run-s lint:fix format
          echo "::set-output name=status::$(git status --porcelain)"
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
