name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install --check-files --frozen-lockfile --non-interactive
      - id: fixpack
        run: yarn fixpack
        continue-on-error: true
      - if: steps.fixpack.outcome == 'failure'
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "bot: fixpack"
          git push origin HEAD
      - id: lint
        run: |
          yarn lint
          echo "::set-output name=status::$(git status --porcelain)"
      - if: steps.lint.outputs.status != ''
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "bot: lint"
          git push origin HEAD
      - run: yarn test
      - id: format
        run: |
          yarn format
          echo "status=$(git diff --shortstat)" >> $GITHUB_OUTPUT
      - if: steps.format.outputs.status != ''
        run: |
          git -c "user.name=github-actions[bot]" -c "user.email=github-actions[bot]@users.noreply.github.com" commit -a -m "bot: format"
          git push origin HEAD
      - run: yarn build
